apiVersion: v1
kind: Service
metadata:
  name: shakee-nginx-service
  namespace: shakee-eks-activity
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80